// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResortManagement.Infrastructure.Data;

#nullable disable

namespace ResortManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250323101359_seedVilla")]
    partial class seedVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResortManagement.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "The Royal Villa features a new kitchen, new bathrooms (5.5), flat screen TVs, interior and exterior paint, lanai furniture, and all linens. Relax like royalty in our sprawling villa that include FOUR KING MASTER bedrooms all with ENSUITE BATHROOMS and flat screen TVs.",
                            ImageURL = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            ID = 2,
                            Description = "Offering sea views, Poolvilla Gaon in Busan provides accommodations, a rooftop pool, an indoor pool, an open-air bath, and a terrace. Built in 2023, the property includes hot spring bath and hot tub. The villa also offers free Wifi, free private parking, and facilities for disabled guests.",
                            ImageURL = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 650
                        },
                        new
                        {
                            ID = 3,
                            Description = "At the villa complex, each unit comes with air conditioning, a seating area, a flat-screen TV with streaming services, a kitchen, a dining area, and a private bathroom with slippers, a shower, and a hair dryer. A microwave, a fridge, and kitchenware are also featured, as well as a coffee machine and a kettle. At the villa complex, all units are fitted with bed linen and towels.",
                            ImageURL = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
