// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResortManagement.Infrastructure.Data;

#nullable disable

namespace ResortManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResortManagement.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("villaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("villaID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Large outdoor pool with temperature control.",
                            Name = "Swimming Pool",
                            villaID = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Fully equipped fitness center.",
                            Name = "Gym",
                            villaID = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Relaxing spa with professional masseurs.",
                            Name = "Spa",
                            villaID = 1
                        },
                        new
                        {
                            ID = 4,
                            Description = "High-speed internet access.",
                            Name = "WiFi",
                            villaID = 2
                        },
                        new
                        {
                            ID = 5,
                            Description = "Spacious balcony with a scenic view.",
                            Name = "Private Balcony",
                            villaID = 2
                        },
                        new
                        {
                            ID = 6,
                            Description = "Stocked mini-bar with refreshments.",
                            Name = "Mini Bar",
                            villaID = 2
                        },
                        new
                        {
                            ID = 7,
                            Description = "Luxury hot tub for relaxation.",
                            Name = "Jacuzzi",
                            villaID = 3
                        },
                        new
                        {
                            ID = 8,
                            Description = "Latest 55-inch Smart TV with streaming services.",
                            Name = "Smart TV",
                            villaID = 3
                        },
                        new
                        {
                            ID = 9,
                            Description = "4/7 room service for your convenience.",
                            Name = "Room Service",
                            villaID = 3
                        });
                });

            modelBuilder.Entity("ResortManagement.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaID")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaID");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaID = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaID = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaID = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            VillaID = 3
                        });
                });

            modelBuilder.Entity("Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "The Royal Villa features a new kitchen, new bathrooms (5.5), flat screen TVs, interior and exterior paint, lanai furniture, and all linens. Relax like royalty in our sprawling villa that include FOUR KING MASTER bedrooms all with ENSUITE BATHROOMS and flat screen TVs.",
                            ImageURL = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            ID = 2,
                            Description = "Offering sea views, Poolvilla Gaon in Busan provides accommodations, a rooftop pool, an indoor pool, an open-air bath, and a terrace. Built in 2023, the property includes hot spring bath and hot tub. The villa also offers free Wifi, free private parking, and facilities for disabled guests.",
                            ImageURL = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 650
                        },
                        new
                        {
                            ID = 3,
                            Description = "At the villa complex, each unit comes with air conditioning, a seating area, a flat-screen TV with streaming services, a kitchen, a dining area, and a private bathroom with slippers, a shower, and a hair dryer. A microwave, a fridge, and kitchenware are also featured, as well as a coffee machine and a kettle. At the villa complex, all units are fitted with bed linen and towels.",
                            ImageURL = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("ResortManagement.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("Villa", "villa")
                        .WithMany()
                        .HasForeignKey("villaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("villa");
                });

            modelBuilder.Entity("ResortManagement.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
